# Generated by Django 4.2.2 on 2023-06-25 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "preco_semana_de",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_semana_por",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_fim_semana_de",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_fim_semana_por",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("regras", models.TextField()),
                ("descricao", models.TextField()),
                ("foto", models.ImageField(upload_to="atracao_fotos/")),
                ("video", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="DadosBancarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.CharField(
                        choices=[("TD", "TED"), ("PX", "PIX")],
                        default="TD",
                        max_length=2,
                    ),
                ),
                ("banco", models.CharField(blank=True, max_length=50, null=True)),
                ("agencia", models.CharField(blank=True, max_length=10, null=True)),
                ("conta", models.CharField(blank=True, max_length=20, null=True)),
                ("chave_pix", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tipo_chave_pix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CL", "Celular"),
                            ("CJ", "CNPJ"),
                            ("EM", "Email"),
                            ("AL", "Chave Aleatória"),
                        ],
                        default="AL",
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dados_bancarios",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rel_empresa",
                        to="empresas.dadosbancarios",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pacote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "preco_semana_de",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_semana_por",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_fim_semana_de",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_fim_semana_por",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("regras", models.TextField()),
                ("descricao", models.TextField()),
                ("foto", models.ImageField(upload_to="pacote_fotos/")),
                ("video", models.URLField()),
                ("atracoes", models.ManyToManyField(to="empresas.atracao")),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cidade", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=10)),
                (
                    "empresa",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dadosbancarios",
            name="empresa",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rel_dados_bancarios",
                to="empresas.empresa",
            ),
        ),
    ]
