# Generated by Django 4.2.2 on 2023-06-25 21:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="admin",
        ),
    ]
