# Generated by Django 4.2.2 on 2023-06-27 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0003_empresa_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pacote",
            name="atracoes",
        ),
        migrations.DeleteModel(
            name="Atracao",
        ),
        migrations.DeleteModel(
            name="Pacote",
        ),
    ]
